import SwiftUI
import WidgetKit

/// Entry point of the watchOS widget extension.
///
/// `@main` on a `WidgetBundle` is the modern replacement for the `NSExtensionPrincipalClass`
/// the Info.plist generated by `@bacons/apple-targets` leaves unset for `watch-widget`
/// targets (it only declares `NSExtensionPointIdentifier = com.apple.widgetkit-extension`).
///
/// One widget today. A second one would be added to `body` below, not to a second target.
@main
struct LucidWatchComplicationBundle: WidgetBundle {
    var body: some Widget {
        StreakComplication()
    }
}
