// ถ่ายจอทุกเส้นทางจาก apps/mobile/dist ด้วย locale ไทย (localStorage lucid.locale) : node scripts/visual-all.js <dist> <outdir> [th|en]
const puppeteer = require('/root/qc/node_modules/puppeteer-core');
const http = require('http'); const fs = require('fs'); const path = require('path');
const [dist, out, lang = 'th'] = process.argv.slice(2);
const ROUTES = [['onboarding','/onboarding?fixture=accepted'],['onboarding-devices','/onboarding/devices?fixture=devices'],['advisor-start','/?fixture=advisor-start'],['advisor-plan','/?fixture=advisor-plan'],['advisor-thinking','/?fixture=advisor-thinking'],['plan','/plan?fixture=plan'],['plan-devices','/plan/devices?fixture=devices'],['ear-left','/plan/ear-left?fixture=ear-passed'],['ear-right','/plan/ear-right?fixture=ear-passed'],['night','/night?fixture=night'],['morning-record','/?fixture=morning-record'],['morning-result','/?fixture=morning-result'],['report','/report/demo?fixture=report'],['journal','/journal?fixture=journal'],['settings','/settings?fixture=devices'],['settings-scrolled','/settings?fixture=devices&scrolled=1'],['find-devices','/plan/find-devices?fixture=ble'],['intro','/?fixture=intro']];
const mime = { '.html':'text/html', '.js':'application/javascript', '.css':'text/css', '.json':'application/json', '.png':'image/png', '.m4a':'audio/mp4', '.wav':'audio/wav', '.ttf':'font/ttf', '.woff2':'font/woff2', '.svg':'image/svg+xml', '.ico':'image/x-icon' };
const srv = http.createServer((req, res) => { let p = decodeURIComponent(req.url.split('?')[0]); let f = path.join(dist, p); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) f = path.join(dist, 'index.html'); res.setHeader('content-type', mime[path.extname(f)] || 'application/octet-stream'); fs.createReadStream(f).pipe(res); });
(async () => { await new Promise(r => srv.listen(0, r)); const port = srv.address().port; fs.mkdirSync(out, { recursive: true });
  const browser = await puppeteer.launch({ executablePath: '/usr/bin/chromium-browser', headless: 'new', args: ['--no-sandbox','--disable-gpu','--hide-scrollbars'] });
  const page = await browser.newPage(); await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
  await page.evaluateOnNewDocument((l) => { try { localStorage.setItem('lucid.locale', l); localStorage.setItem('lucid.onboarding', JSON.stringify({ hasOnboarded: true, consentSafety: { accepted: true, policyVersion: 1, acceptedAt: '2026-09-24T00:00:00Z' }, consentAi: false })); } catch {} }, lang);
  for (const [name, route] of ROUTES) { try { await page.goto(`http://127.0.0.1:${port}${route}`, { waitUntil: 'networkidle0', timeout: 30000 }); await new Promise(r => setTimeout(r, 1200)); const tall = /report|settings|journal/.test(name); if (tall) await page.setViewport({ width: 390, height: 1300, deviceScaleFactor: 1 }); await page.screenshot({ path: path.join(out, `${name}-${lang}.png`) }); if (tall) await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 }); console.log('shot', name); } catch (e) { console.log('FAIL', name, String(e).slice(0, 80)); } }
  await browser.close(); srv.close(); })();
